API: Implement `tensordot` and `matmul`
finch-tensor/finch-jl-python pull request #22
Opened 2024-03-19 18:13 UTC by mtsokol

Tracking issue #21 

Hi @willow-ahrens @hameerabbasi,

This WIP PR introduces `finch.tensordot(x1, x2, axes)` and `finch.matmul(x1, x2)`/`x1 @ x2`.
I still need to complete exhaustive testing. 

---

@willow-ahrens I've got one question regarding `matmul`. I just noticed that there's a slight difference between [`tensordot`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.tensordot.html) and [`matmul`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.matmul.html#array_api.matmul) in Array API for >2D input, namely `tensordot` aggregates non-contracted dims from one input and the other, where `matmul` takes two innermost dims for multiplication, and the rest of dims is treated as a stack/batch dimensions.

Here's a NumPy code showing it:
```python
  >>> a = np.ones([9, 5, 7, 4])
  >>> c = np.ones([9, 5, 4, 3])
  >>> np.tensordot(a, c, axes=((-1,), (-2,))).shape
  (9, 5, 7, 9, 5, 3)
  >>> np.matmul(a, c).shape
  (9, 5, 7, 3)
  >>> # n is 7, k is 4, m is 3
```

So I'm not sure I can implement `matmul` as `self.tensordot(other, axes=((-1,), (-2,)))`. WDYT?

2024-03-19 18:40 UTC, willow-ahrens commented
Yeah, perhaps we need to define einsum better in Finch and express both `matmul` and `tensordot` in terms of that.

Side note:

I think we should implement `mul!` in Julia for Finch Tensor and call that here.

2024-03-26 13:51 UTC, mtsokol commented
@willow-ahrens The PR is ready from my side! (I also want to benchmark these functions)

For now I constrained `matmul` input to 2D tensors, once we have `mul` that can perform matmul on stack of matrices I will recur to this.

2024-03-27 10:24 UTC, hameerabbasi requested changes
Couple of API changes, thanks for the excellent work here, @mtsokol.

2024-03-27 10:24 UTC, hameerabbasi commented on src/finch/__init__.py
> -    multiply,
Is there a reason we're removing `multiply`?

2024-03-27 10:24 UTC, hameerabbasi commented on src/finch/tensor.py
> +            raise ValueError(f"Both tensors must be 2-dimensional, but are: {self.ndim} and {other.ndim}.")
I think this error could be formatted better, it will read like "Both tensors must be 2-dimensional, but are 3 and 4.".
```suggestion
            raise ValueError(f"Both tensors must be 2-dimensional, but: {self.ndim=} and {other.ndim=}.")
```

2024-03-27 10:24 UTC, hameerabbasi commented on src/finch/tensor.py
> +    return x1.tensordot(x2, axes=axes)
Let's make the function form the main one, and remove the method, since it isn't in the Array API or NumPy API.

2024-03-27 10:49 UTC, mtsokol commented on src/finch/__init__.py
> -    multiply,
Haha 😄 accidentally `multiply` got on this list twice.

2024-03-27 11:09 UTC, mtsokol commented on src/finch/tensor.py
> +    return x1.tensordot(x2, axes=axes)
Done!

2024-03-27 11:09 UTC, mtsokol commented on src/finch/tensor.py
> +            raise ValueError(f"Both tensors must be 2-dimensional, but are: {self.ndim} and {other.ndim}.")
Done!

2024-03-27 11:13 UTC, hameerabbasi approved these changes
LGTM, thanks @mtsokol!

2024-03-27 11:52 UTC, merged