Use `jl.permutedims` in `permute_dims`
finch-tensor/finch-jl-python pull request #44
Opened 2024-05-09 10:24 UTC by mtsokol

Hi @hameerabbasi @willow-ahrens,

This small fix makes `permute_dims` use `jl.permutedims` instead of `jl.swizzle`.

It's needed to make transpositions work in the lazy mode, because for `swizzle(lazy(tensor), ...)` we get:

```
ERROR: MethodError: swizzle(::Finch.LazyTensor{Float64, 3}, ::Int64, ::Int64, ::Int64) is ambiguous.

Candidates:
  swizzle(body, dims::Int64...)
    @ Finch ~/JuliaProjects/Finch.jl/src/tensors/combinators/swizzle.jl:80
  swizzle(arr::Finch.LazyTensor, dims...)
    @ Finch ~/JuliaProjects/Finch.jl/src/interface/lazy.jl:63
```

and `permutedims` doesn't raise it.

2024-05-09 16:26 UTC, willow-ahrens commented
I think we should fix that ambiguity error too though. I'll add the issue to finch.jl

2024-05-10 08:58 UTC, mtsokol commented
Sure! For now it's a small fix here in `finch-tensor`.

2024-05-10 09:00 UTC, hameerabbasi requested changes
Can we add a regression test? Something which ensures `permute_dims` will always compile?

2024-05-10 09:25 UTC, mtsokol commented
> Can we add a regression test? Something which ensures `permute_dims` will always compile?

Sure! Done! I extended `test_permute_dims` so it also runs lazy mode (it passes here and fails in a main branch).

2024-05-10 09:29 UTC, hameerabbasi approved these changes

2024-05-10 09:30 UTC, hameerabbasi commented
Thanks for the diagnosis and the work put towards fixing this, @mtsokol!

2024-05-10 09:32 UTC, merged